name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Install Python version 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
